blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
binop_separator = "Front"
brace_style = "SameLineWhere"
color = "Auto"
combine_control_expr = true
comment_width = 100                    # Default 80
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
edition = "2018"
enum_discrim_align_threshold = 0
error_on_line_overflow = false
error_on_unformatted = false
fn_params_layout = "Tall"
fn_single_line = true                  # Default false
force_explicit_abi = true
format_code_in_doc_comments = false
format_generated_files = true
format_macro_bodies = true
format_macro_matchers = false
format_strings = false
group_imports = "StdExternalCrate"     # Default "Preserve"
hard_tabs = false
hex_literal_case = "Preserve"
imports_granularity = "Module"         # Default "Preserve"
imports_indent = "Block"
imports_layout = "Mixed"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = false               # Default true
match_arm_leading_pipes = "Never"
max_width = 100 # This is number of characters.
# `use_small_heuristics` is ignored if the granular width config values are explicitly set.
merge_derives = true
newline_style = "Auto"
normalize_comments = false
normalize_doc_attributes = false
reorder_imports = true
reorder_impl_items = false
reorder_modules = true
remove_nested_parens = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
struct_lit_single_line = true
style_edition = "2018"
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
unstable_features = false
use_field_init_shorthand = false
use_small_heuristics = "Max" # "Max" == All granular width settings same as `max_width`.
use_try_shorthand = false
where_single_line = false
wrap_comments = false